version: "3.9"

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80" # Expose le port 80
    volumes:
      # Mappez le dossier 'ontwikkel' ou 'productie' sur le dossier de Nginx
      - ./ontwikkel/html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

